### ISSUE TITLE
请问这个方法在最新的10.14.5上是否失效了呢？

### ISSUE THREAD

**Issue by ReVe1uv** [nthack/pptp-for-Mac-High-Sierra#1]
测试了几遍不成功，服务器应该没问题。
/etc/ppp/peer这个文件夹不存在

**Comment by nthack** [comment]
Apple MacOS 从`10.15`版本开始在内核里面移除了`PPTP.ppp`内核：（[https://discussions.apple.com/thread/250741630](https://discussions.apple.com/thread/250741630)），我这边在发布这个一段时间之后就没用`PPTP`，转向用`L2TP`协议了，所以有一段时间没用过了。不知道是否在`10.14.5`的时候就撤掉了这个。

在StackExchange里面有人给出了方案，这里给你个链接去看看：(https://apple.stackexchange.com/questions/373110/macos-catalina-pptp-ppp-is-missing)
另外一个网站都指向了VPN Tracker：
（[https://vladtalks.tech/vpn/setup-pptp-vpn-on-mac](https://vladtalks.tech/vpn/setup-pptp-vpn-on-mac)）

> For macOS 10.15 (Catalina): The PPTP library was removed from the macOS kernel.
> * Option 1: Use VPN Tracker, a commercial macOS VPN client.
> * Option 2: Select an alternative VPN protocol.


如果阁下的通道不能换协议的话可以尝试用，不过建议换`L2TP`。

**Comment by ReVe1uv** [comment]
> Apple MacOS 从`10.15`版本开始在内核里面移除了`PPTP.ppp`内核：（https://discussions.apple.com/thread/250741630），我这边在发布这个一段时间之后就没用`PPTP`，转向用`L2TP`协议了，所以有一段时间没用过了。不知道是否在`10.14.5`的时候就撤掉了这个。
> 
> 在StackExchange里面有人给出了方案，这里给你个链接去看看：(https://apple.stackexchange.com/questions/373110/macos-catalina-pptp-ppp-is-missing)
> 另外一个网站都指向了VPN Tracker：
> （https://vladtalks.tech/vpn/setup-pptp-vpn-on-mac）
> 
> > For macOS 10.15 (Catalina): The PPTP library was removed from the macOS kernel.
> > 
> > * Option 1: Use VPN Tracker, a commercial macOS VPN client.
> > * Option 2: Select an alternative VPN protocol.
> 
> 如果阁下的通道不能换协议的话可以尝试用，不过建议换`L2TP`。

感谢，我也换成L2TP协议了。您给的PPTP方案也很有价值。
